spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:h2:mem:notificationdb
    username: pguser
    password: pgpass
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: kafka:29092
    streams:
      application-id: notification-service
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    consumer:
      properties:
        spring.json.trusted.packages: ru.otus.common.events

logging:
  level:
    org.apache.kafka.streams: INFO

app:
  kafka:
    topic:
      payments: payment-service.payments
      dlt: payment-service.payments-dlt
  notification:
    default-type: EMAIL

axon:
  axonserver:
    enabled: false