services:

  postgres-db:
    image: postgres:17-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: pgdb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  axon-server:
    image: axoniq/axonserver:latest
    container_name: axon-server
    ports:
      - "8024:8024"  # HTTP Dashboard (UI)
      - "8124:8124"  # gRPC (Axon apps connect here)
    environment:
      AXONIQ_AXONSERVER_NAME: axon-server
      AXONIQ_AXONSERVER_HOSTNAME: axon-server
    volumes:
      - axon-data:/axonserver/data
      - axon-events:/axonserver/events

volumes:
  pg_data:
  axon-data:
  axon-events:
