### Ищем доступные рейсы
POST http://localhost:8084/api/flights/search
Content-Type: application/json
Accept: application/json

{
  "fromCode": "DXB",
  "toCode": "JFK",
  "departureDate": "2025-06-04T11:30:00Z",
  "returnDate": "2025-06-20T11:30:00Z",
  "passengerCount": 2
}

#### Бронируем рейс
POST http://localhost:8081/api/tickets
Content-Type: application/json

{
  "userId": "aae973ef-9607-43d0-a500-826ca4484b8d",
  "flightNumber": "EK4004",
  "seatNumber": "7B"
}

### Получить детали конкретного бронирования
GET http://localhost:8081/api/tickets/booking/579e1894-4567-4049-9281-3871ffaf1543
Accept: application/json

### Отмена бронирования
POST http://localhost:8081/api/tickets/cancel
Content-Type: application/json

{
  "bookingId": "579e1894-4567-4049-9281-3871ffaf1543",
  "userId": "aae973ef-9607-43d0-a500-826ca4484b8d",
  "flightNumber": "EK4004"
}

### Получить детали конкретного бронирования
GET http://localhost:8081/api/tickets/booking/579e1894-4567-4049-9281-3871ffaf1543
Accept: application/json