### Ищем доступные рейсы
POST http://localhost:8084/api/flights/search
Content-Type: application/json
Accept: application/json

{
  "fromCode": "DXB",
  "toCode": "JFK",
  "departureDate": "2025-08-04T11:30:00Z",
  "returnDate": "2025-08-20T11:30:00Z",
  "passengerCount": 2
}

### Threads info
GET http://localhost:8084/actuator/metrics/executor.pool.size?tag=name:discountExecutor
Accept: application/json

#{
#  "name": "executor.pool.size",
#  "description": "The current number of threads in the pool",
#  "baseUnit": "threads",
#  "measurements": [
#    {
#      "statistic": "VALUE",
#      "value": 2.0
#    }
#  ],
#  "availableTags": [
#    {
#      "tag": "application",
#      "values": [
#        "flight-query-service"
#      ]
#    }
#  ]
#}


#### Бронируем рейс
POST http://localhost:8081/api/tickets
Content-Type: application/json

{
  "userId": "aae973ef-9607-43d0-a500-826ca4484b8d",
  "flightNumber": "EK4004",
  "seatNumber": "23B"
}

### Variables
@bookingId = 5d391b28-9631-4ff6-baf3-8ce92b7bbe4e

### axon_aggregate_identifier=cf2ad83f-3ea9-4a92-9ff2-a9af0bb642fd

### Получить детали конкретного бронирования
GET http://localhost:8081/api/tickets/booking/{{bookingId}}
Accept: application/json

### Отмена бронирования
POST http://localhost:8081/api/tickets/cancel
Content-Type: application/json

{
  "bookingId": "{{bookingId}}",
  "userId": "aae973ef-9607-43d0-a500-826ca4484b8d",
  "flightNumber": "EK4004"
}

### Получить детали конкретного бронирования
GET http://localhost:8081/api/tickets/booking/{{bookingId}}
Accept: application/json