server:
  port: 8083

spring:
  application:
    name: seat-service
  datasource:
    url: jdbc:h2:mem:seatdb
    username: pguser
    password: pgpass
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

axon:
  axonserver:
    enabled: true
    servers: localhost:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson