spring:
  application:
    name: discount-service

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: user
    password: pass
  jpa:
    hibernate:
      ddl-auto: update

axon:
  axonserver:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      access: read_only

  prometheus:
    metrics:
      export:
        enabled: true

discount:
  features:
    early-booking: true
    loyalty: true
    student: true
    summer-discount: false

logging:
  level:
    com.fasterxml.jackson.databind: DEBUG
    org.springframework.http.converter.json: DEBUG
    org.springframework.web: DEBUG
    org.springframework.validation: DEBUG