management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    prometheus:
      access: read_only

  prometheus:
    metrics:
      export:
        enabled: true

discount:
  features:
    early-booking: true
    loyalty: true
    student: true
    promo-code: false
    summer-discount: true
