replicaCount: 1

image:
  repository: localhost:5000/auth-service
  tag: latest
  pullPolicy: Always

containerPort: 8090

service:
  type: NodePort
  port: 8090
  nodePort: 9001

autoscaling:
  enabled: false

livenessProbe:
  httpGet:
    path: /actuator/health
    port: 8090
  initialDelaySeconds: 20
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /actuator/health
    port: 8090
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3