replicaCount: 1

image:
  repository: localhost:5000/auth-service
  tag: latest
  pullPolicy: Always

containerPort: 8080

service:
  type: NodePort
  port: 8080
  nodePort: 9001

autoscaling:
  enabled: false