server:
  port: 8084

spring:
  application:
    name: payment-service

axon:
  axonserver:
    enabled: true
    servers: axon-server:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson