server:
  port: 8082

spring:
  application:
    name: payment-service

axon:
  axonserver:
    enabled: true
    servers: localhost:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson