server:
  port: 8084

app:
  kafka:
    topic:
      payments: payment-service.payments

spring:
  application:
    name: payment-service

axon:
  axonserver:
    enabled: true
    servers: axon-server:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson