server:
  port: 8084

app:
  kafka:
    topic:
      payments: payment-service.payments

spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  datasource:
    url: jdbc:h2:mem:paymentdb
    username: pguser
    password: pgpass
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

axon:
  tracing:
    attribute-providers:
      messageId: true
      messageType: true
      messageName: true
      aggregateIdentifier: true
      payloadType: true
      metadata: true
  axonserver:
    enabled: true
    servers: axon-server:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson

resilience4j:
  ratelimiter:
    instances:
      RPMRateLimiter:
        limitForPeriod: 30
        limitRefreshPeriod: 60s
        timeoutDuration: 0
  circuitbreaker:
    instances:
      defaultCircuitBreaker:
        slidingWindowSize: 10
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
  retry:
    instances:
      paymentRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.lang.RuntimeException

logging:
  level:
    root: INFO
    io.github.resilience4j: DEBUG