{
 "title": "Cache Monitoring",
 "refresh": "5s",
 "panels": [
  {
   "title": "Cache Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cache_size{cache=~\".*\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "cache_requests_hit{cache=~\".*\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache Misses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "cache_requests_miss{cache=~\".*\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Hit Ratio (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "cache_requests_hit{cache=~\".*\"} / (cache_requests_hit{cache=~\".*\"} + cache_requests_miss{cache=~\".*\"}) * 100",
     "legendFormat": "{{cache}}"
    }
   ]
  }
 ]
}