server:
  port: 8081

spring:
  application:
    name: booking-saga-service

axon:
  axonserver:
    enabled: true
    servers: localhost:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson
