server:
  port: 8082

app:
  kafka:
    topic:
      flights: flight-service.flights
      dlt: flight-query-service.dlt

spring:
  application:
    name: flight-query-service

  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: flight-query-service
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    consumer:
      properties:
        spring.json.trusted.packages: ru.otus.common.events


  datasource:
    url: jdbc:h2:mem:flightquerydb
    username: pguser
    password: pgpass
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

axon:
  axonserver:
    enabled: true
    servers: localhost:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson

#logging:
#  level:
#    org.apache.kafka.streams: DEBUG
#    org.apache.kafka.clients: DEBUG
#    org.apache.kafka.common: DEBUG
#    org.apache.kafka.streams.processor.internals.StreamThread: TRACE
