server:
  port: 8082

app:
  kafka:
    topic:
      flights: flight-service.flights
      bookings: flight-service.bookings
      dlt: flight-query-service.dlt

spring:
  application:
    name: flight-query-service

  kafka:
    bootstrap-servers: kafka:29092
    streams:
      application-id: flight-query-service
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    consumer:
      properties:
        spring.json.trusted.packages: ru.otus.common.events


  datasource:
    url: jdbc:h2:mem:flightquerydb
    username: pguser
    password: pgpass
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

axon:
  axonserver:
    enabled: true
    servers: axon-server:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: flight-query-service

logging:
  level:
    org.springframework.cache: DEBUG
    com.github.benmanes.caffeine.cache: TRACE

#logging:
#  level:
#    org.apache.kafka.streams: DEBUG
#    org.apache.kafka.clients: DEBUG
#    org.apache.kafka.common: DEBUG
#    org.apache.kafka.streams.processor.internals.StreamThread: TRACE
