server:
  port: 8085

spring:
  application:
    name: booking-orchestrator-service

axon:
  axonserver:
    enabled: true
    servers: axon-server:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson