server:
  port: 8085

spring:
  application:
    name: booking-orchestrator-service

  datasource:
    url: jdbc:h2:mem:axondb
    username: pguser
    password: pgpass
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: booking-orchestrator-service

axon:
  axonserver:
    enabled: true
    servers: axon-server:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson