### регистрация
POST http://localhost:8090/api/auth/register
Content-Type: application/json

{
  "username": "mortar89",
  "password": "testpassword"
}

### логин
POST http://localhost:8090/api/auth/login
Content-Type: application/json

{
"username": "mortar89",
"password": "testpassword"
}

### refresh
POST http://localhost:8090/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtb3J0YXI4OSIsImlhdCI6MTc0OTM4NzI1NSwiZXhwIjoxNzQ5NDczNjU1fQ.DmInM6E02gX31WLFh6Y12g7OtTPzeRVkjCQhHTfpL9A"
}